require("plugins.packer")
require("plugins.keymaps")
require("plugins.telescope")
require('plugins.gruvbox')
require('plugins.nightfox')
require("plugins.colorscheme")
require("plugins.lualine")
require("plugins.indentline")
require("plugins.neotree")
require("plugins.mason")
require("plugins.jdtls")
require("plugins.lspconfig")
require("plugins.lspzero")
require("plugins.lsp_signature")
require("plugins.zenmode")
require("plugins.gitsigns")
require("plugins.nvim_dap")

