require("plugins.packer")
require("plugins.keymaps")
require("plugins.telescope")
require("plugins.colorscheme")
require("plugins.indentline")
require("plugins.neotree")
require("plugins.mason")
require("plugins.jdtls")
require("plugins.lspconfig")

